# Generated by Django 2.1.7 on 2019-04-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_id',
            field=models.CharField(default='<function now at 0x0361FD68>', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
